apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-secrets # This is the name of the K8s secret it will create
    creationPolicy: Owner
  data:
    - secretKey: encryption-key
      remoteRef:
        key: n8n-encryption-key
