apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
  namespace: n8n
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-db-credentials # This is the name of the K8s secret it will create
    creationPolicy: Owner
  data:
    - secretKey: password # The key inside the K8s Secret
      remoteRef:
        key: n8n-postgres-password # The name of the secret currently in Azure Key Vault
    - secretKey: encryption-key
      remoteRef:
        key: n8n-encryption-key
    - secretKey: username
      remoteRef:
        key: n8n-postgres-username
