apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring

spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: grafana-secrets # This is the name of the K8s secret it will create
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-username: admin
        admin-password: "{{ .grafanaPassword }}"

  data:
    - secretKey: grafanaPassword
      remoteRef:
        key: grafana-password
