apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
  namespace: n8n

spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: n8n-db-credentials
    creationPolicy: Owner
    template:
      mergePolicy: Merge

  data:
    - secretKey: username
      remoteRef:
        key: n8n-postgres-username
    - secretKey: password
      remoteRef:
        key: n8n-postgres-password
