apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgres
  template:
    metadata:
      labels:
        app: n8n-postgres
    spec:
      securityContext:
        # Mount this disk so GID 999 owns it. Required to avoid permission issues
        fsGroup: 999
        fsGroupChangePolicy: "Always"
      # This is required for Postgres to create the directory for its data
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/lib/postgresql/data/pgdata"]
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:16-alpine
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
        - name: POSTGRES_DB
          value: n8n
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: n8n-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-db-credentials
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: n8n-db-pvc
