apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-db
  namespace: n8n
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    primary:
      persistence:
        size: 4Gi
        storageClass: "managed-csi"
      resources: # Limits added here to keep the pod from eating too many resources
        limits:
          memory: 512Mi
          cpu: 250m
        requests:
          memory: 256Mi
          cpu: 100m
